-- TABLA PROYECTOS
CREATE TABLE proyectos (
  id_proyecto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_proyecto VARCHAR2(255) NOT NULL,
  poblacion_total NUMBER(19),
  pct_mujeres NUMBER(10,4),
  pct_rango_edad NUMBER(10,4),
  pct_poblacion_ocupada NUMBER(10,4),
  pct_concentracion_mercado NUMBER(10,4),
  participacion_mercado NUMBER(10,4),
  incremento_poblacion NUMBER(10,4),
  incremento_producto NUMBER(10,4),
  penetracion_inicial NUMBER(10,4),
  incremento_penetracion NUMBER(10,4),
  precio_unitario_base NUMBER(18,4),
  incremento_precio NUMBER(10,4),
  unidades_venta_a1 NUMBER(18,2),
  unidades_venta_a2 NUMBER(18,2),
  unidades_venta_a3 NUMBER(18,2),
  unidades_venta_a4 NUMBER(18,2),
  unidades_venta_a5 NUMBER(18,2),
  dias_credito_ventas NUMBER,
  dias_credito_compras NUMBER,
  descuento_pronto_pago NUMBER(10,4),
  inv_inicial_prod NUMBER(18,2),
  inv_final_a1 NUMBER(18,2),
  inv_final_a2 NUMBER(18,2),
  inv_final_a3 NUMBER(18,2),
  inv_final_a4 NUMBER(18,2),
  inv_final_a5 NUMBER(18,2),
  inv_inicial_mp NUMBER(18,2),
  inv_final_mp_pct NUMBER(10,4),
  tiempo_unidad_mo NUMBER(18,4),
  costo_hora_mo NUMBER(18,4),
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  inversion_inicial NUMBER(18,4),
  saldo_inicial NUMBER(18,4) DEFAULT 0,
  pct_cobro_efectivo NUMBER(10,4) DEFAULT 80,
  inflacion_anual NUMBER(10,4) DEFAULT 0
);

-- TABLA GASTOS ADMIN
CREATE TABLE gastos_administrativos (
  id_gasto_admin NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_id_proyecto NUMBER NOT NULL,
  concepto VARCHAR2(255),
  monto_mensual NUMBER(18,4),
  CONSTRAINT fk_ga_proyecto FOREIGN KEY (fk_id_proyecto) REFERENCES proyectos(id_proyecto) ON DELETE CASCADE
);

-- TABLA GASTOS FIJOS
CREATE TABLE gastos_indirectos_fijos (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_id_proyecto NUMBER NOT NULL,
  concepto VARCHAR2(255),
  monto_anual NUMBER(18,4),
  CONSTRAINT fk_gif_proyecto FOREIGN KEY (fk_id_proyecto) REFERENCES proyectos(id_proyecto) ON DELETE CASCADE
);

-- TABLA GASTOS VARIABLES
CREATE TABLE gastos_indirectos_variables (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_id_proyecto NUMBER NOT NULL,
  concepto VARCHAR2(255),
  por_unidad NUMBER(18,4),
  unidad VARCHAR2(50),
  CONSTRAINT fk_giv_proyecto FOREIGN KEY (fk_id_proyecto) REFERENCES proyectos(id_proyecto) ON DELETE CASCADE
);

-- TABLA GASTOS VENTAS
CREATE TABLE gastos_ventas (
  id_gasto_ventas NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_id_proyecto NUMBER NOT NULL,
  concepto VARCHAR2(255),
  porcentaje_sobre_ventas NUMBER(10,4),
  CONSTRAINT fk_gv_proyecto FOREIGN KEY (fk_id_proyecto) REFERENCES proyectos(id_proyecto) ON DELETE CASCADE
);

-- TABLA INVERSIONES
CREATE TABLE inversiones (
  id_inversion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_id_proyecto NUMBER NOT NULL,
  nombre_activo VARCHAR2(255),
  monto NUMBER(18,4),
  vida_util_anios NUMBER,
  metodo_depreciacion VARCHAR2(50),
  CONSTRAINT fk_inv_proyecto FOREIGN KEY (fk_id_proyecto) REFERENCES proyectos(id_proyecto) ON DELETE CASCADE
);

-- TABLA MATERIAS PRIMAS
CREATE TABLE materias_primas (
  id_materia_prima NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_id_proyecto NUMBER NOT NULL,
  nombre_mp VARCHAR2(255),
  cantidad_por_unidad_prod NUMBER(18,4),
  unidad_medida VARCHAR2(50),
  costo_unitario NUMBER(18,4),
  CONSTRAINT fk_mp_proyecto FOREIGN KEY (fk_id_proyecto) REFERENCES proyectos(id_proyecto) ON DELETE CASCADE
);