version: '3.8'

services:
  # 1. TU SERVIDOR WEB (PHP + Apache)
  web:
    build: .
    container_name: apache_calculadora
    ports:
      - "8080:80"     # Puerto para la página web
      - "8081:8081"   # Puerto para los Sockets
    volumes:
      - .:/var/www/html
    networks:
      - mi_red
    depends_on:
      - db

  # 2. LA NUEVA BASE DE DATOS (ORACLE XE)
  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_db
    environment:
      ORACLE_PASSWORD: admin1234
      APP_USER: usuario_finanzas
      APP_USER_PASSWORD: admin1234
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - mi_red

  # 3. EL ROBOT DE RESPALDOS (DESACTIVADO TEMPORALMENTE)
  # Lo comentamos con # porque mysqldump no sirve para Oracle.
  # cron_backup:
  #   image: alpine:3.19
  #   container_name: sistema_respaldos
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backups:/backups
  #   networks:
  #     - mi_red
  #   command: echo "Backup desactivado por migracion a Oracle"

volumes:
  oracle-data:

networks:
  mi_red:
    driver: bridge