[supervisord]
nodaemon=true

[program:apache]
command=apache2-foreground
priority=10
autostart=true
autorestart=true

[program:websocket]
command=php /var/www/html/bin/server.php
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

# --- NUESTRO NUEVO SISTEMA DE RESPALDOS ---
[program:backup_automatico]
command=/bin/bash /var/www/html/scripts/backup.sh
priority=30
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr