[supervisord]
nodaemon=true

[program:apache]
command=apache2-foreground
priority=10
autostart=true
autorestart=true

[program:websocket]
command=php /var/www/html/bin/server.php
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr